/**
 * Formats a report JSON into a readable Markdown document
 */

export function formatReportAsMarkdown(reportData) {
  const report = reportData.report || reportData;
  
  let markdown = `# Brand Awareness Strategy Report\n\n`;
  markdown += `**Generated:** ${new Date().toLocaleString()}\n`;
  if (reportData.report_id) {
    markdown += `**Report ID:** ${reportData.report_id}\n`;
  }
  markdown += `\n---\n\n`;
  
  // Executive Summary
  if (report.executive_summary) {
    markdown += `## Executive Summary\n\n`;
    markdown += `${report.executive_summary}\n\n`;
    markdown += `---\n\n`;
  }
  
  // Components
  if (report.components && report.components.length > 0) {
    markdown += `## Strategy Components\n\n`;
    
    for (const component of report.components) {
      markdown += `### ${component.title || component.id}\n\n`;
      
      if (component.sections && component.sections.length > 0) {
        for (const section of component.sections) {
          const heading = section.heading || section.title || 'Details';
          markdown += `#### ${heading}\n\n`;
          
          if (section.content) {
            // Format content - handle lists, paragraphs, etc.
            const content = formatContent(section.content);
            markdown += `${content}\n\n`;
          }
        }
      } else if (component.content) {
        markdown += `${formatContent(component.content)}\n\n`;
      }
      
      markdown += `---\n\n`;
    }
  }
  
  // Timeline
  if (report.timeline) {
    markdown += `## Implementation Timeline\n\n`;
    
    if (report.timeline.weeks && Array.isArray(report.timeline.weeks)) {
      for (const week of report.timeline.weeks) {
        if (typeof week === 'object') {
          markdown += `### Week ${week.week || 'N/A'}\n\n`;
          if (week.activities) {
            markdown += `**Activities:** ${week.activities}\n\n`;
          }
          if (week.outcomes) {
            markdown += `**Expected Outcomes:** ${week.outcomes}\n\n`;
          }
        } else {
          markdown += `- ${week}\n`;
        }
      }
    } else if (typeof report.timeline === 'string') {
      markdown += `${report.timeline}\n\n`;
    } else {
      markdown += `${JSON.stringify(report.timeline, null, 2)}\n\n`;
    }
    
    markdown += `---\n\n`;
  }
  
  // Budget Breakdown (if exists)
  if (report.budget_breakdown) {
    markdown += `## Budget Breakdown\n\n`;
    markdown += formatBudgetTable(report.budget_breakdown);
    markdown += `\n---\n\n`;
  }
  
  // Success Metrics (if exists)
  if (report.success_metrics) {
    markdown += `## Success Metrics\n\n`;
    if (Array.isArray(report.success_metrics)) {
      for (const metric of report.success_metrics) {
        markdown += `- **${metric.name || metric}:** ${metric.target || metric.description || ''}\n`;
      }
    } else {
      markdown += `${formatContent(report.success_metrics)}\n\n`;
    }
    markdown += `\n---\n\n`;
  }
  
  // Footer
  markdown += `\n---\n\n`;
  markdown += `*This report was generated by Zansei Marketing Intelligence System.*\n`;
  markdown += `*For questions or support, please contact your marketing advisor.*\n`;
  
  return markdown;
}

function formatContent(content) {
  if (!content) return '';
  
  let formatted = String(content);
  
  // Convert numbered lists (1. item -> 1. item)
  // Convert bullet points (- item -> - item)
  // Split into paragraphs
  const lines = formatted.split('\n');
  const formattedLines = [];
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) {
      formattedLines.push('');
      continue;
    }
    
    // Check if it's already a markdown list item
    if (line.match(/^[-*+]\s/) || line.match(/^\d+\.\s/)) {
      formattedLines.push(line);
    } else if (line.match(/^[A-Z][^.!?]*[.!?]$/)) {
      // Looks like a sentence
      formattedLines.push(line);
    } else {
      // Regular line
      formattedLines.push(line);
    }
  }
  
  return formattedLines.join('\n');
}

function formatBudgetTable(budgetData) {
  if (typeof budgetData === 'string') {
    return budgetData + '\n\n';
  }
  
  if (Array.isArray(budgetData)) {
    let table = '| Channel | Budget | Percentage |\n';
    table += '|---------|--------|------------|\n';
    
    for (const item of budgetData) {
      const channel = item.channel || item.name || 'N/A';
      const budget = item.budget || item.amount || 'N/A';
      const percentage = item.percentage || 'N/A';
      table += `| ${channel} | ${budget} | ${percentage} |\n`;
    }
    
    return table + '\n';
  }
  
  if (typeof budgetData === 'object') {
    let table = '| Channel | Budget |\n';
    table += '|---------|--------|\n';
    
    for (const [channel, budget] of Object.entries(budgetData)) {
      table += `| ${channel} | ${budget} |\n`;
    }
    
    return table + '\n';
  }
  
  return JSON.stringify(budgetData, null, 2) + '\n\n';
}

